/**
 * Interface strings.
 *
 * The French guide is a second build of these same components, so a string written
 * inside a component is the same string in both languages. Anything a reader sees
 * has to live here in src/lib, where the build swaps in the French twin.
 */
export const UI = {
  aRealExample: "UN EXEMPLE RÉEL",
  about: "À propos",
  agile: "Agile",
  alpha: "Alpha",
  andThePartThatIsNotReallyAboutTheGuide: "Et la partie qui ne porte pas vraiment sur le guide",
  ask: "Demander",
  askTheGuide: "Demander au guide",
  assumptionsThisPageMakes: "Les hypothèses de cette page",
  australiaAposSServiceDesignAndDelivery: "Le processus de conception et de prestation de services de l’Australie",
  backToHome: "Retour à l’accueil",
  bad: "Mauvais",
  beta: "Bêta",
  breadcrumb: "Fil d’Ariane",
  browseTheSupportCommunities: "Parcourir les collectivités de soutien →",
  buildStatus: "État de construction",
  canada: "Canada",
  caution: "CAUTION",
  comparison: "Comparaison",
  competition: "Concours",
  contentPlaceholder: "Contenu à venir",
  contractSigned: "Contrat signé :",
  createFromProblemToLaunch: "Création - du problème au lancement",
  describingWhatYouBuy: "Décrire ce que vous achetez",
  digitalLifecycleGuide: "du cycle de vie numérique",
  discovery: "Découverte",
  everyOfficialThingAServiceHasToDoBySub: "Chaque obligation officielle d’un service, par sous-phase",
  example: "Exemple",
  filterByStatus: "Filtrer par état",
  focusAreas: "Domaines prioritaires",
  furtherReading: "Pour aller plus loin",
  github: "GitHub",
  goHome: "Aller à l’accueil",
  good: "Bon",
  governmentOfCanada: "Gouvernement du Canada",
  growth: "Croissance",
  home: "Accueil",
  howASunsetGoes: "Comment se déroule un retrait",
  howItAges: "Comment cela vieillit.",
  howLongItTakes: "COMBIEN DE TEMPS CELA PREND",
  howToReadThisContract: "Comment lire ce contrat",
  index: "Index",
  instrument: "Instrument",
  itAposSDoneWhen: "C’est terminé quand :",
  itStaysYourService: "Le service reste le vôtre.",
  joinedUpDelivery: "Prestation intégrée",
  launch: "LAUNCH",
  launch2: "Lancement",
  live: "Exploitation",
  loadingSearch: "Chargement de la recherche…",
  maturity: "Maturité",
  nadiaIsNotSpecialThisHappensMoreOftenT: "Nadia n’a rien d’exceptionnel : cela arrive plus souvent qu’on ne le croit.",
  needAHandWithThis: "Besoin d’un coup de main ?",
  noPagesWithThisStatusYet: "Aucune page dans cet état pour l’instant.",
  nobodyWasAssignedToManageTheSupplier: "Personne n’a été chargé de gérer le fournisseur.",
  noneOfThatIsWrongItIsACompetentPurchas: "Rien de tout cela n’est erroné. C’est un achat compétent.",
  notSureWhichPhaseYouAreIn: "Vous ne savez pas dans quelle phase vous êtes ?",
  note: "Note",
  nothingMatchedTryAnotherWord: "Aucun résultat. Essayez un autre mot.",
  onThisPage: "Sur cette page",
  oneThingThatCatchesPeopleWhicheverRout: "Une chose qui prend les gens au dépourvu, quelle que soit la voie",
  onlyAvailableOnTheGovernmentOfCanadaNe: "Accessible uniquement sur le réseau du gouvernement du Canada.",
  onlyIf: "Seulement si",
  openAnIssueOnGithub: "Ouvrir un ticket sur GitHub",
  page: "Page",
  phases: "Phases",
  phasesAndSubPhases: "Phases et sous-phases",
  procurementSections: "Sections sur l’approvisionnement",
  references: "Références",
  replaceOrRetirePath: "Voie de remplacement ou de retrait",
  reuseBeforeYouBuyOrBuild: "Réutiliser avant d’acheter ou de construire",
  scope: "Portée",
  searchTheGuide: "Rechercher dans le guide",
  searchTheGuide2: "Rechercher dans le guide…",
  section: "Section:",
  securityByLifecyclePhase: "La sécurité par phase du cycle de vie",
  seeAlso: "Voir aussi",
  seeTheWholePath: "Voir le parcours complet",
  setTheGuideToYourSituation: "Adapter le guide à votre situation",
  shortened: "Abrégé",
  signed: "Signé",
  stabilization: "Stabilisation",
  status: "Status",
  sunset: "Retrait",
  supportAndCommunities: "SOUTIEN ET COLLECTIVITÉS",
  supportAndCommunities2: "Soutien et collectivités",
  the2026: "Le Guide 2026",
  the2026DigitalLifecycleGuide: "Le Guide 2026",
  the2026Guide: "Le Guide 2026",
  theContract: "Le contrat",
  theCostOfSkippingIt: "Ce qu’il en coûte de s’en passer",
  theGuide: "Le guide",
  theOfficialCheckpoints: "LES POINTS DE CONTRÔLE OFFICIELS",
  theOfficialCheckpoints2: "Les points de contrôle officiels.",
  theOfficialCheckpointsOfADigitalServic: "Les points de contrôle officiels d’un service numérique",
  theOneTagThatChangesWhetherARowApplies: "L’étiquette qui décide si une rangée vous concerne",
  theOneThingWorthHoldingOnTo: "La seule chose qu’il vaut la peine de retenir",
  theSameProgrammeBoughtTwoWays: "Le même programme, acheté de deux façons",
  theSchedules: "Les annexes",
  theSecurityPractices: "Les pratiques de sécurité.",
  theThreePhases: "Les trois phases",
  theThreeSubPhasesOfLive: "Les trois sous-phases de l’Exploitation",
  thisGuideIsForYouWhateverBroughtYouHer: "Ce guide est pour vous, quelle que soit la raison de votre venue",
  thisPageDidnTLoad: "Cette page ne s’est pas chargée",
  thisPageWanderedOff: "Cette page s’est égarée",
  thisSourceIsOnItsWay: "Cette source s’en vient",
  todo: "TODO",
  topic: "Sujet",
  traditional: "Traditionnel",
  traditionalAndAgile: "Traditionnel et agile",
  traditionalAndAgileComparison: "Comparaison traditionnel et agile",
  tryAgain: "Réessayer",
  type: "Type",
  typeAPageNameOrAPhraseFromTheGuide: "Tapez un nom de page ou une expression du guide.",
  underReview: "EN RÉVISION",
  unitedKingdomAposSServiceManual: "Le Service Manual du Royaume-Uni",
  whatBringsItIntoScope: "Ce qui le fait entrer dans la portée",
  whatEachOneIsCalledAndWhoHasToProduceI: "Le nom de chacun, et qui doit le produire",
  whatGoodLooksLike: "À quoi ressemble la réussite",
  whatIsHereForYouWhicheverWayYouGo: "Ce qu’il y a ici pour vous, quelle que soit la voie",
  whatItIs: "Ce que c’est",
  whatKindOfThingEachOneIs: "De quel type est chacun",
  whatNadiaDoes: "Ce que fait Nadia",
  whatTheBusinessOwnerDoes: "Ce que fait le responsable opérationnel",
  whatTheTagsMean: "Ce que signifient les étiquettes",
  whatThisGuideIs: "Ce qu’est ce guide",
  whenItComesUp: "Quand cela survient",
  whereThisFits: "Où cela s’inscrit",
  whoDoesTheWork: "Qui fait le travail",
  whoPays: "Qui paie",
  whoRespondsAndHow: "Qui intervient, et comment",
  whoThisIsFor: "À qui cela s’adresse",
  whoseJobItIs: "À qui revient ce travail",
  whyItMatters: "Pourquoi cela compte",
  whyWeCouldNotSimplyFollowTheUkAndAustr: "Pourquoi nous ne pouvions pas simplement suivre le Royaume-Uni et l’Australie",
  youMightBe: "Vous êtes peut-être :",
  theStepsOfAProcurement: "Les étapes d’un approvisionnement",
  theOfficialInstrumentsBehind: "Les instruments officiels derrière",
  searchShort: "Rechercher",
  aFewOfTheRoutesShowingWhereTheCompetit: "Quelques-unes des voies, montrant où se déroule le concours et où le contrat est signé",
  aPractitionerSGuideToTheDigitalService: "Un guide pratique du cycle de vie d’un service numérique au gouvernement du Canada.",
  betaEndsHereTheServiceBecomesTheOffici: "La Bêta se termine ici. Le service devient le service officiel, de vraies personnes en dépendent, et le ministère en répond à partir de ce moment jusqu’à son remplacement ou son retrait.",
  choosingToMakeYourOwnInsteadBreaksNoRu: "Choisir de fabriquer le vôtre n’enfreint aucune règle. Le cadre de l’architecture intégrée demande toutefois aux équipes d’examiner d’abord la réutilisation : un comité d’examen de l’architecture du ministère demandera probablement lesquels de ces éléments ont été envisagés et pourquoi aucun ne convenait.",
  everythingOfficialThisSubjectBringsWit: "Tout ce que ce sujet apporte d’officiel, et à quel moment de la vie d’un service chaque élément survient. Le détail complet, y compris qui fait le travail et ce que le responsable opérationnel fait personnellement, se trouve dans le tableau de la page d’accueil.",
  gettingAServiceLiveMeansPassingOfficia: "Mettre un service en exploitation suppose de franchir des points de contrôle officiels : évaluations à mener, comités à rencontrer, registres où figurer, et obligations qui durent aussi longtemps que le service. Lesquels s’appliquent dépend de ce que fait le service et de ce qui est dépensé : deux services n’empruntent donc jamais le même parcours.",
  internalBuildTrackerForEveryPageInTheG: "Suivi interne de construction pour chaque page du guide, y compris les ébauches qui ne sont liées à aucune navigation ordinaire. L’index destiné aux lecteurs se trouve sous Index dans l’en-tête.",
  lookForSomethingToReuseBeforeMakingYou: "Cherchez quelque chose à réutiliser avant de fabriquer le vôtre. Voici les pièces déjà construites et entretenues par une autre partie du gouvernement : une équipe peut donc configurer plutôt que fabriquer. Le tableau des instruments officiels est ce avec quoi un service doit composer. Ceci est ce qu’il peut éviter d’avoir à fabriquer.",
  oneCautionWhichSubPhaseAnInstrumentBel: "Une mise en garde. La sous-phase à laquelle appartient un instrument relève du jugement propre à ce guide, parce qu’aucune source du gouvernement du Canada n’emploie ces noms de phases. Là où le placement suit une véritable échéance inscrite dans l’instrument, la rangée le dit. Là où ce n’est pas le cas, la rangée le dit aussi.",
  oneTablePerTopicBelowAndEveryInstrumen: "Un tableau par sujet ci-dessous, et chaque instrument y occupe deux rangées. La rangée du haut dit ce qui le fait entrer dans la portée, ce que vous devez personnellement faire à son sujet, et qui fait le reste. La rangée du dessous dit ce qu’est la chose, et à quel moment de la vie du service elle survient.",
  placingAnInstrumentInASubPhaseIsThisGu: "Placer un instrument dans une sous-phase est un choix éditorial propre à ce guide, ancré autant que possible sur une véritable échéance inscrite dans l’instrument lui-même. Le détail complet, y compris qui fait le travail et ce que le responsable opérationnel fait personnellement, se trouve dans le tableau complet des instruments.",
  somethingWentWrongOnOurEndYouCanTryRef: "Quelque chose a mal tourné de notre côté. Vous pouvez essayer d’actualiser ou revenir à l’accueil.",
  thePageYouAreLookingForDoesNotExistOrI: "La page que vous cherchez n’existe pas, ou elle a peut-être déménagé. Dans un cas comme dans l’autre, elle n’est pas ici.",
  theThreeKindsOfRequirementWhatEachOneS: "Les trois catégories d’exigences, ce que chacune dit, et à quelle vitesse chacune se périme",
  thisGuideIsAWorkInProgressSpottedSomet: "Ce guide est en chantier. Vous avez remarqué quelque chose qui cloche, ou vous avez des commentaires ?",
  thisInstrumentDoesNotApplyToEveryServi: "Cet instrument ne s’applique pas à tous les services. La colonne de la portée dit ce qui le fait entrer dans la portée. Un instrument sans étiquette s’applique à tous.",
  thisPageIsStillToComeItWillCoverWhatIt: "Cette page s’en vient. Elle portera sur ce que veut dire conserver assez de compréhension pour gouverner le travail et pour gérer une sortie.",
  thisTableIsWideTurnThePhoneSidewaysToR: "Ce tableau est large. Tournez le téléphone sur le côté pour le lire, et faites défiler horizontalement à l’intérieur du tableau pour atteindre les dernières colonnes.",
  aGuideForTheNextGuide: "Un guide pour le prochain guide",
  anIndependentGuideNotAnOfficial: "Un guide indépendant. Il ne s’agit pas d’une publication officielle du gouvernement du Canada.",
  nobodyToldHer: "Personne ne le lui a dit",
  noteAccurateForNow: "Ceci est un guide de 2026, exact pour le moment. Des liens peuvent se périmer à mesure que des instruments sont renommés et que des pages changent d’adresse, mais les concepts tiennent. C’est aussi une version préliminaire, construite au grand jour : nous cherchons donc vos commentaires :",
  subBetaCreate: "Sous-phase Bêta (Création)",
  subMaturityLive: "Sous-phase Maturité (Exploitation)",
  tellUsWhatIsMissing: "dites-nous ce qui manque, ce qui est faux ou ce qui n’est pas clair",
  theOfficialInstrumentsIn: "Les instruments officiels dans",
  theOfficialCheckpointsPlain: "Les points de contrôle officiels",
  aPictureOfWhatIsComing: "Un aperçu de ce qui s’en vient.",
  forYourSetup: "Pour votre configuration",
  rightIsWhoAnswersAndHowTheTagOnEachRes: "À droite, qui intervient et comment. L’étiquette de chaque intervention dit si l’intervenant est",
  timelineShowingDiscoveryAlphaAndBetaMa: "Chronologie montrant la Découverte, l’Alpha et la Bêta qui composent la phase de Création (environ 6 à 12 mois), puis l’Exploitation avec ses sous-phases Stabilisation, Croissance et Maturité, et le Retrait, toutes deux sans durée déterminée",
  whatWorkStaysYours: "Quel travail reste le vôtre",
} as const;
