/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SunsetRouteImport } from './routes/sunset'
import { Route as SourceComingSoonRouteImport } from './routes/source-coming-soon'
import { Route as LiveStabilizationRouteImport } from './routes/live-stabilization'
import { Route as LiveMaturityRouteImport } from './routes/live-maturity'
import { Route as LiveGrowthRouteImport } from './routes/live-growth'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GateMapRouteImport } from './routes/gate-map'
import { Route as CreateDiscoveryRouteImport } from './routes/create-discovery'
import { Route as CreateDesignForTheWholeJourneyRouteImport } from './routes/create-design-for-the-whole-journey'
import { Route as CreateBetaRouteImport } from './routes/create-beta'
import { Route as CreateAlphaRouteImport } from './routes/create-alpha'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AllPagesRouteImport } from './routes/all-pages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadProcurementRouteImport } from './routes/thread.procurement'
import { Route as ThreadContractingRouteImport } from './routes/thread.contracting'
import { Route as ThreadSlugRouteImport } from './routes/thread.$slug'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as ReferenceTreasuryBoardSubmissionRouteImport } from './routes/reference.treasury-board-submission'
import { Route as ReferenceStayingFundedRouteImport } from './routes/reference.staying-funded'
import { Route as ReferenceSooVsSowRouteImport } from './routes/reference.soo-vs-sow'
import { Route as ReferenceOptionsAnalysisRouteImport } from './routes/reference.options-analysis'
import { Route as ReferenceFundingTheExitRouteImport } from './routes/reference.funding-the-exit'
import { Route as ReferenceDesignForTheWholeJourneyRouteImport } from './routes/reference.design-for-the-whole-journey'
import { Route as ReferenceCostingAServiceRouteImport } from './routes/reference.costing-a-service'
import { Route as ReferenceApprovalJourneyRouteImport } from './routes/reference.approval-journey'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as ThreadProcurementIndexRouteImport } from './routes/thread.procurement.index'
import { Route as ThreadContractingIndexRouteImport } from './routes/thread.contracting.index'
import { Route as ThreadProcurementGoodContractRouteImport } from './routes/thread.procurement.good-contract'
import { Route as ThreadProcurementPageRouteImport } from './routes/thread.procurement.$page'
import { Route as ThreadFundingTreasuryBoardSubmissionRouteImport } from './routes/thread.funding.treasury-board-submission'
import { Route as ThreadFundingStayingFundedRouteImport } from './routes/thread.funding.staying-funded'
import { Route as ThreadFundingFundingTheExitRouteImport } from './routes/thread.funding.funding-the-exit'
import { Route as ThreadFundingCostingAServiceRouteImport } from './routes/thread.funding.costing-a-service'
import { Route as ThreadContractingPageRouteImport } from './routes/thread.contracting.$page'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SunsetRoute = SunsetRouteImport.update({
  id: '/sunset',
  path: '/sunset',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceComingSoonRoute = SourceComingSoonRouteImport.update({
  id: '/source-coming-soon',
  path: '/source-coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStabilizationRoute = LiveStabilizationRouteImport.update({
  id: '/live-stabilization',
  path: '/live-stabilization',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMaturityRoute = LiveMaturityRouteImport.update({
  id: '/live-maturity',
  path: '/live-maturity',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveGrowthRoute = LiveGrowthRouteImport.update({
  id: '/live-growth',
  path: '/live-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GateMapRoute = GateMapRouteImport.update({
  id: '/gate-map',
  path: '/gate-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDiscoveryRoute = CreateDiscoveryRouteImport.update({
  id: '/create-discovery',
  path: '/create-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDesignForTheWholeJourneyRoute =
  CreateDesignForTheWholeJourneyRouteImport.update({
    id: '/create-design-for-the-whole-journey',
    path: '/create-design-for-the-whole-journey',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateBetaRoute = CreateBetaRouteImport.update({
  id: '/create-beta',
  path: '/create-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAlphaRoute = CreateAlphaRouteImport.update({
  id: '/create-alpha',
  path: '/create-alpha',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPagesRoute = AllPagesRouteImport.update({
  id: '/all-pages',
  path: '/all-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadProcurementRoute = ThreadProcurementRouteImport.update({
  id: '/thread/procurement',
  path: '/thread/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadContractingRoute = ThreadContractingRouteImport.update({
  id: '/thread/contracting',
  path: '/thread/contracting',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadSlugRoute = ThreadSlugRouteImport.update({
  id: '/thread/$slug',
  path: '/thread/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceTreasuryBoardSubmissionRoute =
  ReferenceTreasuryBoardSubmissionRouteImport.update({
    id: '/reference/treasury-board-submission',
    path: '/reference/treasury-board-submission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceStayingFundedRoute = ReferenceStayingFundedRouteImport.update({
  id: '/reference/staying-funded',
  path: '/reference/staying-funded',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSooVsSowRoute = ReferenceSooVsSowRouteImport.update({
  id: '/reference/soo-vs-sow',
  path: '/reference/soo-vs-sow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceOptionsAnalysisRoute =
  ReferenceOptionsAnalysisRouteImport.update({
    id: '/reference/options-analysis',
    path: '/reference/options-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceFundingTheExitRoute = ReferenceFundingTheExitRouteImport.update({
  id: '/reference/funding-the-exit',
  path: '/reference/funding-the-exit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceDesignForTheWholeJourneyRoute =
  ReferenceDesignForTheWholeJourneyRouteImport.update({
    id: '/reference/design-for-the-whole-journey',
    path: '/reference/design-for-the-whole-journey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceCostingAServiceRoute =
  ReferenceCostingAServiceRouteImport.update({
    id: '/reference/costing-a-service',
    path: '/reference/costing-a-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceApprovalJourneyRoute =
  ReferenceApprovalJourneyRouteImport.update({
    id: '/reference/approval-journey',
    path: '/reference/approval-journey',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadProcurementIndexRoute = ThreadProcurementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadProcurementRoute,
} as any)
const ThreadContractingIndexRoute = ThreadContractingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadContractingRoute,
} as any)
const ThreadProcurementGoodContractRoute =
  ThreadProcurementGoodContractRouteImport.update({
    id: '/good-contract',
    path: '/good-contract',
    getParentRoute: () => ThreadProcurementRoute,
  } as any)
const ThreadProcurementPageRoute = ThreadProcurementPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ThreadProcurementRoute,
} as any)
const ThreadFundingTreasuryBoardSubmissionRoute =
  ThreadFundingTreasuryBoardSubmissionRouteImport.update({
    id: '/thread/funding/treasury-board-submission',
    path: '/thread/funding/treasury-board-submission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThreadFundingStayingFundedRoute =
  ThreadFundingStayingFundedRouteImport.update({
    id: '/thread/funding/staying-funded',
    path: '/thread/funding/staying-funded',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThreadFundingFundingTheExitRoute =
  ThreadFundingFundingTheExitRouteImport.update({
    id: '/thread/funding/funding-the-exit',
    path: '/thread/funding/funding-the-exit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThreadFundingCostingAServiceRoute =
  ThreadFundingCostingAServiceRouteImport.update({
    id: '/thread/funding/costing-a-service',
    path: '/thread/funding/costing-a-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThreadContractingPageRoute = ThreadContractingPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ThreadContractingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-beta': typeof CreateBetaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/gate-map': typeof GateMapRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/support': typeof SupportRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/approval-journey': typeof ReferenceApprovalJourneyRoute
  '/reference/costing-a-service': typeof ReferenceCostingAServiceRoute
  '/reference/design-for-the-whole-journey': typeof ReferenceDesignForTheWholeJourneyRoute
  '/reference/funding-the-exit': typeof ReferenceFundingTheExitRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/reference/staying-funded': typeof ReferenceStayingFundedRoute
  '/reference/treasury-board-submission': typeof ReferenceTreasuryBoardSubmissionRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting': typeof ThreadContractingRouteWithChildren
  '/thread/procurement': typeof ThreadProcurementRouteWithChildren
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/funding/costing-a-service': typeof ThreadFundingCostingAServiceRoute
  '/thread/funding/funding-the-exit': typeof ThreadFundingFundingTheExitRoute
  '/thread/funding/staying-funded': typeof ThreadFundingStayingFundedRoute
  '/thread/funding/treasury-board-submission': typeof ThreadFundingTreasuryBoardSubmissionRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/procurement/good-contract': typeof ThreadProcurementGoodContractRoute
  '/thread/contracting/': typeof ThreadContractingIndexRoute
  '/thread/procurement/': typeof ThreadProcurementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-beta': typeof CreateBetaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/gate-map': typeof GateMapRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/support': typeof SupportRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/approval-journey': typeof ReferenceApprovalJourneyRoute
  '/reference/costing-a-service': typeof ReferenceCostingAServiceRoute
  '/reference/design-for-the-whole-journey': typeof ReferenceDesignForTheWholeJourneyRoute
  '/reference/funding-the-exit': typeof ReferenceFundingTheExitRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/reference/staying-funded': typeof ReferenceStayingFundedRoute
  '/reference/treasury-board-submission': typeof ReferenceTreasuryBoardSubmissionRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/funding/costing-a-service': typeof ThreadFundingCostingAServiceRoute
  '/thread/funding/funding-the-exit': typeof ThreadFundingFundingTheExitRoute
  '/thread/funding/staying-funded': typeof ThreadFundingStayingFundedRoute
  '/thread/funding/treasury-board-submission': typeof ThreadFundingTreasuryBoardSubmissionRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/procurement/good-contract': typeof ThreadProcurementGoodContractRoute
  '/thread/contracting': typeof ThreadContractingIndexRoute
  '/thread/procurement': typeof ThreadProcurementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-beta': typeof CreateBetaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/gate-map': typeof GateMapRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/support': typeof SupportRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/approval-journey': typeof ReferenceApprovalJourneyRoute
  '/reference/costing-a-service': typeof ReferenceCostingAServiceRoute
  '/reference/design-for-the-whole-journey': typeof ReferenceDesignForTheWholeJourneyRoute
  '/reference/funding-the-exit': typeof ReferenceFundingTheExitRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/reference/staying-funded': typeof ReferenceStayingFundedRoute
  '/reference/treasury-board-submission': typeof ReferenceTreasuryBoardSubmissionRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting': typeof ThreadContractingRouteWithChildren
  '/thread/procurement': typeof ThreadProcurementRouteWithChildren
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/funding/costing-a-service': typeof ThreadFundingCostingAServiceRoute
  '/thread/funding/funding-the-exit': typeof ThreadFundingFundingTheExitRoute
  '/thread/funding/staying-funded': typeof ThreadFundingStayingFundedRoute
  '/thread/funding/treasury-board-submission': typeof ThreadFundingTreasuryBoardSubmissionRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/procurement/good-contract': typeof ThreadProcurementGoodContractRoute
  '/thread/contracting/': typeof ThreadContractingIndexRoute
  '/thread/procurement/': typeof ThreadProcurementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-beta'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/gate-map'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/support'
    | '/practice/$slug'
    | '/reference/approval-journey'
    | '/reference/costing-a-service'
    | '/reference/design-for-the-whole-journey'
    | '/reference/funding-the-exit'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/reference/staying-funded'
    | '/reference/treasury-board-submission'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting'
    | '/thread/procurement'
    | '/thread/contracting/$page'
    | '/thread/funding/costing-a-service'
    | '/thread/funding/funding-the-exit'
    | '/thread/funding/staying-funded'
    | '/thread/funding/treasury-board-submission'
    | '/thread/procurement/$page'
    | '/thread/procurement/good-contract'
    | '/thread/contracting/'
    | '/thread/procurement/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-beta'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/gate-map'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/support'
    | '/practice/$slug'
    | '/reference/approval-journey'
    | '/reference/costing-a-service'
    | '/reference/design-for-the-whole-journey'
    | '/reference/funding-the-exit'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/reference/staying-funded'
    | '/reference/treasury-board-submission'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting/$page'
    | '/thread/funding/costing-a-service'
    | '/thread/funding/funding-the-exit'
    | '/thread/funding/staying-funded'
    | '/thread/funding/treasury-board-submission'
    | '/thread/procurement/$page'
    | '/thread/procurement/good-contract'
    | '/thread/contracting'
    | '/thread/procurement'
  id:
    | '__root__'
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-beta'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/gate-map'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/support'
    | '/practice/$slug'
    | '/reference/approval-journey'
    | '/reference/costing-a-service'
    | '/reference/design-for-the-whole-journey'
    | '/reference/funding-the-exit'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/reference/staying-funded'
    | '/reference/treasury-board-submission'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting'
    | '/thread/procurement'
    | '/thread/contracting/$page'
    | '/thread/funding/costing-a-service'
    | '/thread/funding/funding-the-exit'
    | '/thread/funding/staying-funded'
    | '/thread/funding/treasury-board-submission'
    | '/thread/procurement/$page'
    | '/thread/procurement/good-contract'
    | '/thread/contracting/'
    | '/thread/procurement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllPagesRoute: typeof AllPagesRoute
  CreateRoute: typeof CreateRoute
  CreateAlphaRoute: typeof CreateAlphaRoute
  CreateBetaRoute: typeof CreateBetaRoute
  CreateDesignForTheWholeJourneyRoute: typeof CreateDesignForTheWholeJourneyRoute
  CreateDiscoveryRoute: typeof CreateDiscoveryRoute
  GateMapRoute: typeof GateMapRoute
  LiveRoute: typeof LiveRoute
  LiveGrowthRoute: typeof LiveGrowthRoute
  LiveMaturityRoute: typeof LiveMaturityRoute
  LiveStabilizationRoute: typeof LiveStabilizationRoute
  SourceComingSoonRoute: typeof SourceComingSoonRoute
  SunsetRoute: typeof SunsetRoute
  SupportRoute: typeof SupportRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  ReferenceApprovalJourneyRoute: typeof ReferenceApprovalJourneyRoute
  ReferenceCostingAServiceRoute: typeof ReferenceCostingAServiceRoute
  ReferenceDesignForTheWholeJourneyRoute: typeof ReferenceDesignForTheWholeJourneyRoute
  ReferenceFundingTheExitRoute: typeof ReferenceFundingTheExitRoute
  ReferenceOptionsAnalysisRoute: typeof ReferenceOptionsAnalysisRoute
  ReferenceSooVsSowRoute: typeof ReferenceSooVsSowRoute
  ReferenceStayingFundedRoute: typeof ReferenceStayingFundedRoute
  ReferenceTreasuryBoardSubmissionRoute: typeof ReferenceTreasuryBoardSubmissionRoute
  ReviewSlugRoute: typeof ReviewSlugRoute
  ThreadSlugRoute: typeof ThreadSlugRoute
  ThreadContractingRoute: typeof ThreadContractingRouteWithChildren
  ThreadProcurementRoute: typeof ThreadProcurementRouteWithChildren
  ThreadFundingCostingAServiceRoute: typeof ThreadFundingCostingAServiceRoute
  ThreadFundingFundingTheExitRoute: typeof ThreadFundingFundingTheExitRoute
  ThreadFundingStayingFundedRoute: typeof ThreadFundingStayingFundedRoute
  ThreadFundingTreasuryBoardSubmissionRoute: typeof ThreadFundingTreasuryBoardSubmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunset': {
      id: '/sunset'
      path: '/sunset'
      fullPath: '/sunset'
      preLoaderRoute: typeof SunsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-coming-soon': {
      id: '/source-coming-soon'
      path: '/source-coming-soon'
      fullPath: '/source-coming-soon'
      preLoaderRoute: typeof SourceComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-stabilization': {
      id: '/live-stabilization'
      path: '/live-stabilization'
      fullPath: '/live-stabilization'
      preLoaderRoute: typeof LiveStabilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-maturity': {
      id: '/live-maturity'
      path: '/live-maturity'
      fullPath: '/live-maturity'
      preLoaderRoute: typeof LiveMaturityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-growth': {
      id: '/live-growth'
      path: '/live-growth'
      fullPath: '/live-growth'
      preLoaderRoute: typeof LiveGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-map': {
      id: '/gate-map'
      path: '/gate-map'
      fullPath: '/gate-map'
      preLoaderRoute: typeof GateMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-discovery': {
      id: '/create-discovery'
      path: '/create-discovery'
      fullPath: '/create-discovery'
      preLoaderRoute: typeof CreateDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-design-for-the-whole-journey': {
      id: '/create-design-for-the-whole-journey'
      path: '/create-design-for-the-whole-journey'
      fullPath: '/create-design-for-the-whole-journey'
      preLoaderRoute: typeof CreateDesignForTheWholeJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-beta': {
      id: '/create-beta'
      path: '/create-beta'
      fullPath: '/create-beta'
      preLoaderRoute: typeof CreateBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-alpha': {
      id: '/create-alpha'
      path: '/create-alpha'
      fullPath: '/create-alpha'
      preLoaderRoute: typeof CreateAlphaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-pages': {
      id: '/all-pages'
      path: '/all-pages'
      fullPath: '/all-pages'
      preLoaderRoute: typeof AllPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/procurement': {
      id: '/thread/procurement'
      path: '/thread/procurement'
      fullPath: '/thread/procurement'
      preLoaderRoute: typeof ThreadProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/contracting': {
      id: '/thread/contracting'
      path: '/thread/contracting'
      fullPath: '/thread/contracting'
      preLoaderRoute: typeof ThreadContractingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$slug': {
      id: '/thread/$slug'
      path: '/thread/$slug'
      fullPath: '/thread/$slug'
      preLoaderRoute: typeof ThreadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/treasury-board-submission': {
      id: '/reference/treasury-board-submission'
      path: '/reference/treasury-board-submission'
      fullPath: '/reference/treasury-board-submission'
      preLoaderRoute: typeof ReferenceTreasuryBoardSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/staying-funded': {
      id: '/reference/staying-funded'
      path: '/reference/staying-funded'
      fullPath: '/reference/staying-funded'
      preLoaderRoute: typeof ReferenceStayingFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/soo-vs-sow': {
      id: '/reference/soo-vs-sow'
      path: '/reference/soo-vs-sow'
      fullPath: '/reference/soo-vs-sow'
      preLoaderRoute: typeof ReferenceSooVsSowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/options-analysis': {
      id: '/reference/options-analysis'
      path: '/reference/options-analysis'
      fullPath: '/reference/options-analysis'
      preLoaderRoute: typeof ReferenceOptionsAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/funding-the-exit': {
      id: '/reference/funding-the-exit'
      path: '/reference/funding-the-exit'
      fullPath: '/reference/funding-the-exit'
      preLoaderRoute: typeof ReferenceFundingTheExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/design-for-the-whole-journey': {
      id: '/reference/design-for-the-whole-journey'
      path: '/reference/design-for-the-whole-journey'
      fullPath: '/reference/design-for-the-whole-journey'
      preLoaderRoute: typeof ReferenceDesignForTheWholeJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/costing-a-service': {
      id: '/reference/costing-a-service'
      path: '/reference/costing-a-service'
      fullPath: '/reference/costing-a-service'
      preLoaderRoute: typeof ReferenceCostingAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/approval-journey': {
      id: '/reference/approval-journey'
      path: '/reference/approval-journey'
      fullPath: '/reference/approval-journey'
      preLoaderRoute: typeof ReferenceApprovalJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/procurement/': {
      id: '/thread/procurement/'
      path: '/'
      fullPath: '/thread/procurement/'
      preLoaderRoute: typeof ThreadProcurementIndexRouteImport
      parentRoute: typeof ThreadProcurementRoute
    }
    '/thread/contracting/': {
      id: '/thread/contracting/'
      path: '/'
      fullPath: '/thread/contracting/'
      preLoaderRoute: typeof ThreadContractingIndexRouteImport
      parentRoute: typeof ThreadContractingRoute
    }
    '/thread/procurement/good-contract': {
      id: '/thread/procurement/good-contract'
      path: '/good-contract'
      fullPath: '/thread/procurement/good-contract'
      preLoaderRoute: typeof ThreadProcurementGoodContractRouteImport
      parentRoute: typeof ThreadProcurementRoute
    }
    '/thread/procurement/$page': {
      id: '/thread/procurement/$page'
      path: '/$page'
      fullPath: '/thread/procurement/$page'
      preLoaderRoute: typeof ThreadProcurementPageRouteImport
      parentRoute: typeof ThreadProcurementRoute
    }
    '/thread/funding/treasury-board-submission': {
      id: '/thread/funding/treasury-board-submission'
      path: '/thread/funding/treasury-board-submission'
      fullPath: '/thread/funding/treasury-board-submission'
      preLoaderRoute: typeof ThreadFundingTreasuryBoardSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/funding/staying-funded': {
      id: '/thread/funding/staying-funded'
      path: '/thread/funding/staying-funded'
      fullPath: '/thread/funding/staying-funded'
      preLoaderRoute: typeof ThreadFundingStayingFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/funding/funding-the-exit': {
      id: '/thread/funding/funding-the-exit'
      path: '/thread/funding/funding-the-exit'
      fullPath: '/thread/funding/funding-the-exit'
      preLoaderRoute: typeof ThreadFundingFundingTheExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/funding/costing-a-service': {
      id: '/thread/funding/costing-a-service'
      path: '/thread/funding/costing-a-service'
      fullPath: '/thread/funding/costing-a-service'
      preLoaderRoute: typeof ThreadFundingCostingAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/contracting/$page': {
      id: '/thread/contracting/$page'
      path: '/$page'
      fullPath: '/thread/contracting/$page'
      preLoaderRoute: typeof ThreadContractingPageRouteImport
      parentRoute: typeof ThreadContractingRoute
    }
  }
}

interface ThreadContractingRouteChildren {
  ThreadContractingPageRoute: typeof ThreadContractingPageRoute
  ThreadContractingIndexRoute: typeof ThreadContractingIndexRoute
}

const ThreadContractingRouteChildren: ThreadContractingRouteChildren = {
  ThreadContractingPageRoute: ThreadContractingPageRoute,
  ThreadContractingIndexRoute: ThreadContractingIndexRoute,
}

const ThreadContractingRouteWithChildren =
  ThreadContractingRoute._addFileChildren(ThreadContractingRouteChildren)

interface ThreadProcurementRouteChildren {
  ThreadProcurementPageRoute: typeof ThreadProcurementPageRoute
  ThreadProcurementGoodContractRoute: typeof ThreadProcurementGoodContractRoute
  ThreadProcurementIndexRoute: typeof ThreadProcurementIndexRoute
}

const ThreadProcurementRouteChildren: ThreadProcurementRouteChildren = {
  ThreadProcurementPageRoute: ThreadProcurementPageRoute,
  ThreadProcurementGoodContractRoute: ThreadProcurementGoodContractRoute,
  ThreadProcurementIndexRoute: ThreadProcurementIndexRoute,
}

const ThreadProcurementRouteWithChildren =
  ThreadProcurementRoute._addFileChildren(ThreadProcurementRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllPagesRoute: AllPagesRoute,
  CreateRoute: CreateRoute,
  CreateAlphaRoute: CreateAlphaRoute,
  CreateBetaRoute: CreateBetaRoute,
  CreateDesignForTheWholeJourneyRoute: CreateDesignForTheWholeJourneyRoute,
  CreateDiscoveryRoute: CreateDiscoveryRoute,
  GateMapRoute: GateMapRoute,
  LiveRoute: LiveRoute,
  LiveGrowthRoute: LiveGrowthRoute,
  LiveMaturityRoute: LiveMaturityRoute,
  LiveStabilizationRoute: LiveStabilizationRoute,
  SourceComingSoonRoute: SourceComingSoonRoute,
  SunsetRoute: SunsetRoute,
  SupportRoute: SupportRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  ReferenceApprovalJourneyRoute: ReferenceApprovalJourneyRoute,
  ReferenceCostingAServiceRoute: ReferenceCostingAServiceRoute,
  ReferenceDesignForTheWholeJourneyRoute:
    ReferenceDesignForTheWholeJourneyRoute,
  ReferenceFundingTheExitRoute: ReferenceFundingTheExitRoute,
  ReferenceOptionsAnalysisRoute: ReferenceOptionsAnalysisRoute,
  ReferenceSooVsSowRoute: ReferenceSooVsSowRoute,
  ReferenceStayingFundedRoute: ReferenceStayingFundedRoute,
  ReferenceTreasuryBoardSubmissionRoute: ReferenceTreasuryBoardSubmissionRoute,
  ReviewSlugRoute: ReviewSlugRoute,
  ThreadSlugRoute: ThreadSlugRoute,
  ThreadContractingRoute: ThreadContractingRouteWithChildren,
  ThreadProcurementRoute: ThreadProcurementRouteWithChildren,
  ThreadFundingCostingAServiceRoute: ThreadFundingCostingAServiceRoute,
  ThreadFundingFundingTheExitRoute: ThreadFundingFundingTheExitRoute,
  ThreadFundingStayingFundedRoute: ThreadFundingStayingFundedRoute,
  ThreadFundingTreasuryBoardSubmissionRoute:
    ThreadFundingTreasuryBoardSubmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
