/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SunsetRouteImport } from './routes/sunset'
import { Route as SourceComingSoonRouteImport } from './routes/source-coming-soon'
import { Route as LiveStabilizationRouteImport } from './routes/live-stabilization'
import { Route as LiveMaturityRouteImport } from './routes/live-maturity'
import { Route as LiveGrowthRouteImport } from './routes/live-growth'
import { Route as LiveRouteImport } from './routes/live'
import { Route as CreateMvpRouteImport } from './routes/create-mvp'
import { Route as CreateDiscoveryRouteImport } from './routes/create-discovery'
import { Route as CreateDesignForTheWholeJourneyRouteImport } from './routes/create-design-for-the-whole-journey'
import { Route as CreateAlphaRouteImport } from './routes/create-alpha'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AllPagesRouteImport } from './routes/all-pages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadProcurementRouteImport } from './routes/thread.procurement'
import { Route as ThreadContractingRouteImport } from './routes/thread.contracting'
import { Route as ThreadSlugRouteImport } from './routes/thread.$slug'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as ReferenceSooVsSowRouteImport } from './routes/reference.soo-vs-sow'
import { Route as ReferenceOptionsAnalysisRouteImport } from './routes/reference.options-analysis'
import { Route as ReferenceManagingWhatYouBoughtRouteImport } from './routes/reference.managing-what-you-bought'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as ThreadProcurementIndexRouteImport } from './routes/thread.procurement.index'
import { Route as ThreadContractingIndexRouteImport } from './routes/thread.contracting.index'
import { Route as ThreadProcurementPageRouteImport } from './routes/thread.procurement.$page'
import { Route as ThreadContractingPageRouteImport } from './routes/thread.contracting.$page'

const SunsetRoute = SunsetRouteImport.update({
  id: '/sunset',
  path: '/sunset',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceComingSoonRoute = SourceComingSoonRouteImport.update({
  id: '/source-coming-soon',
  path: '/source-coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStabilizationRoute = LiveStabilizationRouteImport.update({
  id: '/live-stabilization',
  path: '/live-stabilization',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMaturityRoute = LiveMaturityRouteImport.update({
  id: '/live-maturity',
  path: '/live-maturity',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveGrowthRoute = LiveGrowthRouteImport.update({
  id: '/live-growth',
  path: '/live-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMvpRoute = CreateMvpRouteImport.update({
  id: '/create-mvp',
  path: '/create-mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDiscoveryRoute = CreateDiscoveryRouteImport.update({
  id: '/create-discovery',
  path: '/create-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDesignForTheWholeJourneyRoute =
  CreateDesignForTheWholeJourneyRouteImport.update({
    id: '/create-design-for-the-whole-journey',
    path: '/create-design-for-the-whole-journey',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateAlphaRoute = CreateAlphaRouteImport.update({
  id: '/create-alpha',
  path: '/create-alpha',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPagesRoute = AllPagesRouteImport.update({
  id: '/all-pages',
  path: '/all-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadProcurementRoute = ThreadProcurementRouteImport.update({
  id: '/thread/procurement',
  path: '/thread/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadContractingRoute = ThreadContractingRouteImport.update({
  id: '/thread/contracting',
  path: '/thread/contracting',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadSlugRoute = ThreadSlugRouteImport.update({
  id: '/thread/$slug',
  path: '/thread/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSooVsSowRoute = ReferenceSooVsSowRouteImport.update({
  id: '/reference/soo-vs-sow',
  path: '/reference/soo-vs-sow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceOptionsAnalysisRoute =
  ReferenceOptionsAnalysisRouteImport.update({
    id: '/reference/options-analysis',
    path: '/reference/options-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceManagingWhatYouBoughtRoute =
  ReferenceManagingWhatYouBoughtRouteImport.update({
    id: '/reference/managing-what-you-bought',
    path: '/reference/managing-what-you-bought',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadProcurementIndexRoute = ThreadProcurementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadProcurementRoute,
} as any)
const ThreadContractingIndexRoute = ThreadContractingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadContractingRoute,
} as any)
const ThreadProcurementPageRoute = ThreadProcurementPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ThreadProcurementRoute,
} as any)
const ThreadContractingPageRoute = ThreadContractingPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ThreadContractingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/create-mvp': typeof CreateMvpRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/managing-what-you-bought': typeof ReferenceManagingWhatYouBoughtRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting': typeof ThreadContractingRouteWithChildren
  '/thread/procurement': typeof ThreadProcurementRouteWithChildren
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/contracting/': typeof ThreadContractingIndexRoute
  '/thread/procurement/': typeof ThreadProcurementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/create-mvp': typeof CreateMvpRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/managing-what-you-bought': typeof ReferenceManagingWhatYouBoughtRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/contracting': typeof ThreadContractingIndexRoute
  '/thread/procurement': typeof ThreadProcurementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-pages': typeof AllPagesRoute
  '/create': typeof CreateRoute
  '/create-alpha': typeof CreateAlphaRoute
  '/create-design-for-the-whole-journey': typeof CreateDesignForTheWholeJourneyRoute
  '/create-discovery': typeof CreateDiscoveryRoute
  '/create-mvp': typeof CreateMvpRoute
  '/live': typeof LiveRoute
  '/live-growth': typeof LiveGrowthRoute
  '/live-maturity': typeof LiveMaturityRoute
  '/live-stabilization': typeof LiveStabilizationRoute
  '/source-coming-soon': typeof SourceComingSoonRoute
  '/sunset': typeof SunsetRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/reference/managing-what-you-bought': typeof ReferenceManagingWhatYouBoughtRoute
  '/reference/options-analysis': typeof ReferenceOptionsAnalysisRoute
  '/reference/soo-vs-sow': typeof ReferenceSooVsSowRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/thread/$slug': typeof ThreadSlugRoute
  '/thread/contracting': typeof ThreadContractingRouteWithChildren
  '/thread/procurement': typeof ThreadProcurementRouteWithChildren
  '/thread/contracting/$page': typeof ThreadContractingPageRoute
  '/thread/procurement/$page': typeof ThreadProcurementPageRoute
  '/thread/contracting/': typeof ThreadContractingIndexRoute
  '/thread/procurement/': typeof ThreadProcurementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/create-mvp'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/practice/$slug'
    | '/reference/managing-what-you-bought'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting'
    | '/thread/procurement'
    | '/thread/contracting/$page'
    | '/thread/procurement/$page'
    | '/thread/contracting/'
    | '/thread/procurement/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/create-mvp'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/practice/$slug'
    | '/reference/managing-what-you-bought'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting/$page'
    | '/thread/procurement/$page'
    | '/thread/contracting'
    | '/thread/procurement'
  id:
    | '__root__'
    | '/'
    | '/all-pages'
    | '/create'
    | '/create-alpha'
    | '/create-design-for-the-whole-journey'
    | '/create-discovery'
    | '/create-mvp'
    | '/live'
    | '/live-growth'
    | '/live-maturity'
    | '/live-stabilization'
    | '/source-coming-soon'
    | '/sunset'
    | '/practice/$slug'
    | '/reference/managing-what-you-bought'
    | '/reference/options-analysis'
    | '/reference/soo-vs-sow'
    | '/review/$slug'
    | '/thread/$slug'
    | '/thread/contracting'
    | '/thread/procurement'
    | '/thread/contracting/$page'
    | '/thread/procurement/$page'
    | '/thread/contracting/'
    | '/thread/procurement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllPagesRoute: typeof AllPagesRoute
  CreateRoute: typeof CreateRoute
  CreateAlphaRoute: typeof CreateAlphaRoute
  CreateDesignForTheWholeJourneyRoute: typeof CreateDesignForTheWholeJourneyRoute
  CreateDiscoveryRoute: typeof CreateDiscoveryRoute
  CreateMvpRoute: typeof CreateMvpRoute
  LiveRoute: typeof LiveRoute
  LiveGrowthRoute: typeof LiveGrowthRoute
  LiveMaturityRoute: typeof LiveMaturityRoute
  LiveStabilizationRoute: typeof LiveStabilizationRoute
  SourceComingSoonRoute: typeof SourceComingSoonRoute
  SunsetRoute: typeof SunsetRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  ReferenceManagingWhatYouBoughtRoute: typeof ReferenceManagingWhatYouBoughtRoute
  ReferenceOptionsAnalysisRoute: typeof ReferenceOptionsAnalysisRoute
  ReferenceSooVsSowRoute: typeof ReferenceSooVsSowRoute
  ReviewSlugRoute: typeof ReviewSlugRoute
  ThreadSlugRoute: typeof ThreadSlugRoute
  ThreadContractingRoute: typeof ThreadContractingRouteWithChildren
  ThreadProcurementRoute: typeof ThreadProcurementRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sunset': {
      id: '/sunset'
      path: '/sunset'
      fullPath: '/sunset'
      preLoaderRoute: typeof SunsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-coming-soon': {
      id: '/source-coming-soon'
      path: '/source-coming-soon'
      fullPath: '/source-coming-soon'
      preLoaderRoute: typeof SourceComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-stabilization': {
      id: '/live-stabilization'
      path: '/live-stabilization'
      fullPath: '/live-stabilization'
      preLoaderRoute: typeof LiveStabilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-maturity': {
      id: '/live-maturity'
      path: '/live-maturity'
      fullPath: '/live-maturity'
      preLoaderRoute: typeof LiveMaturityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-growth': {
      id: '/live-growth'
      path: '/live-growth'
      fullPath: '/live-growth'
      preLoaderRoute: typeof LiveGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-mvp': {
      id: '/create-mvp'
      path: '/create-mvp'
      fullPath: '/create-mvp'
      preLoaderRoute: typeof CreateMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-discovery': {
      id: '/create-discovery'
      path: '/create-discovery'
      fullPath: '/create-discovery'
      preLoaderRoute: typeof CreateDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-design-for-the-whole-journey': {
      id: '/create-design-for-the-whole-journey'
      path: '/create-design-for-the-whole-journey'
      fullPath: '/create-design-for-the-whole-journey'
      preLoaderRoute: typeof CreateDesignForTheWholeJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-alpha': {
      id: '/create-alpha'
      path: '/create-alpha'
      fullPath: '/create-alpha'
      preLoaderRoute: typeof CreateAlphaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-pages': {
      id: '/all-pages'
      path: '/all-pages'
      fullPath: '/all-pages'
      preLoaderRoute: typeof AllPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/procurement': {
      id: '/thread/procurement'
      path: '/thread/procurement'
      fullPath: '/thread/procurement'
      preLoaderRoute: typeof ThreadProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/contracting': {
      id: '/thread/contracting'
      path: '/thread/contracting'
      fullPath: '/thread/contracting'
      preLoaderRoute: typeof ThreadContractingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$slug': {
      id: '/thread/$slug'
      path: '/thread/$slug'
      fullPath: '/thread/$slug'
      preLoaderRoute: typeof ThreadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/soo-vs-sow': {
      id: '/reference/soo-vs-sow'
      path: '/reference/soo-vs-sow'
      fullPath: '/reference/soo-vs-sow'
      preLoaderRoute: typeof ReferenceSooVsSowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/options-analysis': {
      id: '/reference/options-analysis'
      path: '/reference/options-analysis'
      fullPath: '/reference/options-analysis'
      preLoaderRoute: typeof ReferenceOptionsAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/managing-what-you-bought': {
      id: '/reference/managing-what-you-bought'
      path: '/reference/managing-what-you-bought'
      fullPath: '/reference/managing-what-you-bought'
      preLoaderRoute: typeof ReferenceManagingWhatYouBoughtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/procurement/': {
      id: '/thread/procurement/'
      path: '/'
      fullPath: '/thread/procurement/'
      preLoaderRoute: typeof ThreadProcurementIndexRouteImport
      parentRoute: typeof ThreadProcurementRoute
    }
    '/thread/contracting/': {
      id: '/thread/contracting/'
      path: '/'
      fullPath: '/thread/contracting/'
      preLoaderRoute: typeof ThreadContractingIndexRouteImport
      parentRoute: typeof ThreadContractingRoute
    }
    '/thread/procurement/$page': {
      id: '/thread/procurement/$page'
      path: '/$page'
      fullPath: '/thread/procurement/$page'
      preLoaderRoute: typeof ThreadProcurementPageRouteImport
      parentRoute: typeof ThreadProcurementRoute
    }
    '/thread/contracting/$page': {
      id: '/thread/contracting/$page'
      path: '/$page'
      fullPath: '/thread/contracting/$page'
      preLoaderRoute: typeof ThreadContractingPageRouteImport
      parentRoute: typeof ThreadContractingRoute
    }
  }
}

interface ThreadContractingRouteChildren {
  ThreadContractingPageRoute: typeof ThreadContractingPageRoute
  ThreadContractingIndexRoute: typeof ThreadContractingIndexRoute
}

const ThreadContractingRouteChildren: ThreadContractingRouteChildren = {
  ThreadContractingPageRoute: ThreadContractingPageRoute,
  ThreadContractingIndexRoute: ThreadContractingIndexRoute,
}

const ThreadContractingRouteWithChildren =
  ThreadContractingRoute._addFileChildren(ThreadContractingRouteChildren)

interface ThreadProcurementRouteChildren {
  ThreadProcurementPageRoute: typeof ThreadProcurementPageRoute
  ThreadProcurementIndexRoute: typeof ThreadProcurementIndexRoute
}

const ThreadProcurementRouteChildren: ThreadProcurementRouteChildren = {
  ThreadProcurementPageRoute: ThreadProcurementPageRoute,
  ThreadProcurementIndexRoute: ThreadProcurementIndexRoute,
}

const ThreadProcurementRouteWithChildren =
  ThreadProcurementRoute._addFileChildren(ThreadProcurementRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllPagesRoute: AllPagesRoute,
  CreateRoute: CreateRoute,
  CreateAlphaRoute: CreateAlphaRoute,
  CreateDesignForTheWholeJourneyRoute: CreateDesignForTheWholeJourneyRoute,
  CreateDiscoveryRoute: CreateDiscoveryRoute,
  CreateMvpRoute: CreateMvpRoute,
  LiveRoute: LiveRoute,
  LiveGrowthRoute: LiveGrowthRoute,
  LiveMaturityRoute: LiveMaturityRoute,
  LiveStabilizationRoute: LiveStabilizationRoute,
  SourceComingSoonRoute: SourceComingSoonRoute,
  SunsetRoute: SunsetRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  ReferenceManagingWhatYouBoughtRoute: ReferenceManagingWhatYouBoughtRoute,
  ReferenceOptionsAnalysisRoute: ReferenceOptionsAnalysisRoute,
  ReferenceSooVsSowRoute: ReferenceSooVsSowRoute,
  ReviewSlugRoute: ReviewSlugRoute,
  ThreadSlugRoute: ThreadSlugRoute,
  ThreadContractingRoute: ThreadContractingRouteWithChildren,
  ThreadProcurementRoute: ThreadProcurementRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
